### ISSUE TITLE
When would the config file be made available?

### ISSUE THREAD

**Issue by Cascol-SCUT** [google-research/vmoe#1]
As title..

**Comment by jpuigcerver** [comment]
I have also added a config file to transfer the model pre-trained on ImageNet-21k to CIFAR-10. 

This config was made to have minimal hardware requirements: it runs on a TPUv3-8 in about 10 minutes.

Check c30c873edd8416f6a5af134f963136147a468c3c.

**Comment by Cascol-SCUT** [comment]
Thanks so much, I'll check it out.

**Comment by gongbudaizhe** [comment]
will the train from scratch config be available?

**Comment by jpuigcerver** [comment]
Apologies for taking so long to reply.

We have uploaded a [config file](https://github.com/google-research/vmoe/blob/652f8bd5ec2ee5b7733f23d1cf733bc362099e1a/vmoe/configs/vmoe_paper/vmoe_s32_last2_ilsvrc2012_randaug_light1.py) to train a small ViT-S/32, with 2 layers of MoEs, on ILSVRC2012 from-scratch (ImageNet21k is not available in Tensorflow Datasets at this moment, unfortunately).

We have also released the corresponding checkpoint after training (`gs://vmoe_checkpoints/vmoe_s32_last2_ilsvrc2012_randaug_light1`), as well as a checkpoint after fine-tuning the previous on higher resolution (`gs://vmoe_checkpoints/vmoe_s32_last2_ilsvrc2012_randaug_light1_ft_ilsvrc2012`, and its corresponding [config file](https://github.com/google-research/vmoe/blob/652f8bd5ec2ee5b7733f23d1cf733bc362099e1a/vmoe/configs/vmoe_paper/vmoe_s32_last2_ilsvrc2012_randaug_light1_ft_ilsvrc2012.py)).
