### ISSUE TITLE
Could you guys provide a pytorch version?

### ISSUE THREAD

**Issue by DoctorLiQ** [google-research/vmoe#145]
Tensorflow is hard to install even with conda.

**Comment by daixiangzi** [comment]
+1

**Comment by jpuigcerver** [comment]
Unfortunately, we don't have the manpower to work on an efficient PyTorch implementation at this moment.

Other people have implemented V-MoE and Soft MoE on PyTorch and have made the code available on GitHub, but I haven't tried those out myself. So, I cannot comment on whether the implementations are equivalent or not.
