### ISSUE TITLE
There is no function with name 'initialize_from_vmoe_release' within the file 'initialization.py'

### ISSUE THREAD

**Issue by nowazrabbani** [google-research/vmoe#156]
In the config file for finetuning the ensemble model, the model is about to initialize using the function name 'initialize_from_vmoe_release'. But, there is no such function with the file 'initialization.py' which preventing the fine-tuning. Can you please look into that. Thank you.

**Comment by jpuigcerver** [comment]
This was fixed a while back, the correct name is `initialize_from_vmoe`. We've updated the config files for fine-tuning, please take a look at them.
